# Generated by Django 5.1.7 on 2025-04-22 13:08

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(upload_to='faq_img')),
                ('img2', models.ImageField(upload_to='faq_img')),
            ],
        ),
        migrations.CreateModel(
            name='Featured',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='featured-images')),
            ],
        ),
        migrations.CreateModel(
            name='MyService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('icon', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='blog_post')),
                ('date', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('body', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('PUBLISH', 'PUBLISH')], default='DRAFT', max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
